apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
  labels:
    app: {{ .Values.app.labelPrefix }}/{{ .Release.Name }}
spec:
  minAvailable: {{ sub .Values.replicaCount 1 }}
  selector:
    matchLabels:
      app: {{ .Values.app.labelPrefix }}/{{ .Release.Name }}