apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priority.className }}
value: {{ .Values.priority.value }}
globalDefault: false
description: "High priority class for critical workloads"