name: release

on:
  push:
    branches: [ main ]

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore: release changes')"
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      run: ./release.sh
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Commit release changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes to commit
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git add -A
          git commit -m "chore: release changes"
          git push
        fi